### ISSUE TITLE
403 Client error Forbidden for URL

### ISSUE THREAD

**Issue by mkschulze** [impredicative/bitlyshortener#1]
Hello,

I try to set up URL shortening in the following way:

```
from bitlyshortener import Shortener
tokens_pool = 'my_general_access_token'  # is this correct?
shortener = Shortener(tokens=tokens_pool, max_cache_size=8192)
```

```
@usr_account.route("/account/createtable", methods=["POST"])
def account_createtable():
    form = CreateTableForm(request.form)
    if form.validate():
        tableid = DB.add_table(form.tablenumber.data, current_user.get_id())
        new_url = config.base_url + "newrequest/" + tableid
        short_url = shortener.shorten_urls(new_url)
        DB.update_table(tableid, short_url)
        return redirect(url_for('account.account'))
    return render_template("account.html", createtableform=form, tables=DB.get_tables(current_user.get_id()))
```

This gives me the following error:

https://gist.github.com/mark-schulze/b02b9c77dd45046dc932eaf195e4bf34

`requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api-ssl.bitly.com/v4/bitlinks`

and

`bitlyshortener.exc.RequestError: Exhausted all 30 attempts requesting response from 30 for long URL h. The error is: HTTPError: 403 Client Error: Forbidden for url: https://api-ssl.bitly.com/v4/bitlinks`

I'm not sure if I properly bind in the access_token or what could cause the error.
If you could help me here, it would be great.

I do get another error, I post a separated issue for that.

Thanks

**Comment by impredicative** [comment]
Refer to https://github.com/impredicative/bitlyshortener/issues/2

If that doesn't help, please post another comment.
