### ISSUE TITLE
only first occurency done, others error

### ISSUE THREAD

**Issue by itajackass** [impredicative/bitlyshortener#10]
I've an array of urls to cicle
Due to specification of my project, i need to pass only 1 url at time.
First result i get correct
second one cycle get this error:

```
    237         num_short_urls = len(short_urls)
    238         assert num_long_urls == num_short_urls
--> 239         urls_per_second = num_short_urls / time_used
    240         log.info(
    241             "%s retrieved %s short URLs%s in %.1fs at a rate of %.0f/s. %s",

ZeroDivisionError: float division by zero
```

**Comment by impredicative** [comment]
No support will be provided to the offensive username. This issue will be deleted. You must use an inoffensive username to request support.

**Comment by itajackass** [comment]
> No support will be provided to the offensive username. This issue will be deleted. You must use an inoffensive username to request support.

Jackass is a tv show! Ita is for italian!

**Comment by impredicative** [comment]
I tested it and the issue couldn't be reproduced. There is no way that exactly 0 seconds can be used even for a cache hit; It's just impossible.

Anyway, further supported cannot be provided to this username. Production companies and teams don't use offensive names even if the name of the TV show is offensive.
