### ISSUE TITLE
Support Python 3.6.9

### ISSUE THREAD

**Issue by schneiderfelipe** [impredicative/bitlyshortener#11]
Currently, bitlyshortener supports only Python 3.7+. Is there a reason for it? Can shortening happen serially if `ThreadPoolExecutor` throws an error?

Python 3.6.9 is still *very* much used, as being, for instance, the standard version in Ubuntu 18.04 LTS.

**Comment by impredicative** [comment]
This is not going to happen in this repo. This package will not even install with the older version of Python.

Isn't Ubuntu 18.04 old? I read that Ubuntu 20.04 has Python 3.8. Anyway, it is trivially easy to install a newer Python on Ubuntu. Do you need help with this? Why are you using the older Python?

If you really cannot update Python, I advise forking this repo.

**Comment by schneiderfelipe** [comment]
> This is not going to happen in this repo. This package will not even install with the older version of Python.

Because [`setup.py` says so](https://github.com/impredicative/bitlyshortener/blob/14755166ee2a99ea9e2718e8944c698cc51cb2ff/setup.py#L29).

> Isn't Ubuntu 18.04 old? I read that Ubuntu 20.04 has Python 3.8. Anyway, it is trivially easy to install a newer Python on Ubuntu. Do you need help with this? Why are you using the older Python?

[Ubuntu 18.04 was the main LTS (long-term supported) release until April 23rd, 2020 (exactly two weeks ago). Now it is 20.04, but 18.04 will have full support until 2023.](https://wiki.ubuntu.com/Releases)

If you require people to use Python 3.7+, [you might be missing over 80% of Python 3 users](https://w3techs.com/technologies/details/pl-python/3).

> If you really cannot update Python, I advise forking this repo.

Thank you for the advice. I ended up using [`pyshorteners`](https://pyshorteners.readthedocs.io/en/latest/).

**Comment by impredicative** [comment]
This package is for very high volume shortening using multiple Bitly tokens. If you don't need to do this, then you don't need this package.

It is irrational to deprive yourself of the benefits of newer versions of Python.
