### ISSUE TITLE
shorten_urls ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by llazzaro** [impredicative/bitlyshortener#12]
When using `shorten_urls` I got a division by zero. 

Variables has the following values:

```
num_short_urls
1
time_used
0.0
```

Here is the traceback:

```
Traceback (most recent call last):
  File "I:\scraper\venv\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "I:\scraper\venv\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "I:\scraper\venv\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "I:/scraper/scraper/amazon/amazon.py", line 39, in main
    for product in products:
  File "I:\scraper\scraper\amazon\__init__.py", line 114, in search_amazon
    shorten_url = shortener.shorten_urls([url]).pop
  File "I:\scraper\venv\lib\site-packages\bitlyshortener\shortener.py", line 239, in shorten_urls
    urls_per_second = num_short_urls / time_used
ZeroDivisionError: float division by zero
```

I made a fix this this bug, let me know if you need a PR.

**Comment by impredicative** [comment]
What is the version of Python used, the version of this package used, the OS name and version, and the long URL? Also, why are you using `.pop` instead of `[0]`?

**Comment by llazzaro** [comment]
OS: `Windows 10`
package version: `0.3`
Python version `3.7.1`
Long url: 

> https://www.amazon.com/GeeMo-Super-Suction-mins-Running-Super-Capacity-G201/dp/B083DMX2QL/ref=sr_1_1_sspa?dchild=1&keywords=vacuum+cleaner&qid=1589303389&sr=8-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUExSlhZN0RDNlNVSVNVJmVuY3J5cHRlZElkPUEwMzY0ODE4T0laUklQSkQ3VkszJmVuY3J5cHRlZEFkSWQ9QTAxOTIzMjMxWFcwODZJRTNWMEY5JndpZGdldE5hbWU9c3BfYXRmJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==

Tried with pop() and [0], both of them fail with the same error. I like to use pop.

When using a debugger `time_used` is bigger than 0 and makes sense. 
But when I run the script, the division error is triggered with high probability. Sometimes works due to OS context switching I think.

**Comment by llazzaro** [comment]
BTW sorry for using windows, pretty sure this will work with Linux

**Comment by impredicative** [comment]
Amazon products already have a natural short URL. For example, the short URL to the long link you posted is https://amzn.com/B083DMX2QL/ . You can produce such a short URL using a simple regex alone.

Given the above info, do you still need this package?

**Comment by llazzaro** [comment]
It doesn't matter if the link comes from amazon, the code will fail with any link. 

The link you provided in the answer will be useless for me since I will lose all the tracking information that bitly provides.

**Comment by llazzaro** [comment]
Closing since I started to use a more stable api client.

**Comment by impredicative** [comment]
You shouldn't have filed an issue if you didn't need it fixed. This client is extremely stable under Linux. If your operating system is returning bad times, that's not a fault of this client. In any case, I guess you don't need this issue fixed anymore.
