### ISSUE TITLE
Customize shortened URL

### ISSUE THREAD

**Issue by madzul** [impredicative/bitlyshortener#16]
How to use customize back half with this library?

**Comment by impredicative** [comment]
I don't understand your question. Please be clear.

**Comment by madzul** [comment]
Custom Bitlink (CMIIW)
We can create shortened URL in bitly with keyword ("custom back half"), like bit.ly/MyKey123. Can we do that with this library?
TY

**Comment by impredicative** [comment]
No. This software doesn't implement that feature, and there are no current plans to implement it.
