### ISSUE TITLE
ZeroDivisionError when long url is in cache

### ISSUE THREAD

**Issue by FRIKIdelTO** [impredicative/bitlyshortener#19]
Tried processing only one long url twice:

```
  File "C:\python\lib\site-packages\bitlyshortener\shortener.py", line 270, in shorten_urls
    rate_per_second = num_short_urls / time_used
ZeroDivisionError: float division by zero
```

My manual solution editing "shortener.py" at line 270:
```
        try:
            rate_per_second = num_short_urls / time_used
        except ZeroDivisionError:
            rate_per_second = 1
```

**Comment by impredicative** [comment]
Are you using one of:

- a 16 or 32 bit CPU
- a special distribution of Python
- a low-resolution hardware clock

**Comment by impredicative** [comment]
Anyway, this risk has been mitigated in the new release 0.6.1. I will let you close this issue after trying this new release.

**Comment by FRIKIdelTO** [comment]
> Are you using one of:
> 
> * a 16 or 32 bit CPU
> * a special distribution of Python
> * a low-resolution hardware clock

- 64bit CPU

- Python 3.9.7 on Windows 10 Pro x64

 ```
time.monotonic()
541588.171
```

0.6.1 version works very fine.
Thanks for fix it so fast and much better than me ;-)

**Comment by impredicative** [comment]
Thank you for the report!
