### ISSUE TITLE
"KeyError: 'organizations'" when checking usage

### ISSUE THREAD

**Issue by manojsitapara** [impredicative/bitlyshortener#20]
shortener.usage() method give organizations key error

Am I missing something?

**Comment by manojsitapara** [comment]
```
shortener = Shortener(tokens=tokens_pools, max_cache_size=8192)
quota = shortener.usage()
```

This how I did it, nothing special, It was working earlier, now suddenly stopped

**Comment by manojsitapara** [comment]
ohh Sorry I misunderstood !! yes I have created token as procedure noted in the readme

**Comment by manojsitapara** [comment]
Okay Thank you for your quick response. I really appreciate

**Comment by impredicative** [comment]
I am unable to reproduce the issue. It worked fine for me. If you want you can share an affected token with me here, and I will check it.

**Comment by manojsitapara** [comment]
Sure here are both tokens

0acfb2ca51ce2430d9ec38a5a7245bb0d1579303
2e4bfe6183670ffdd86b28b27189453d50b8a605

**Comment by impredicative** [comment]
The second token above works fine.

The first token above has the error:

```
  File "/home/codespace/.local/lib/python3.10/site-packages/cachetools/func.py", line 62, in wrapper
    v = func(*args, **kwargs)
  File "/workspaces/bitlyshortener/bitlyshortener/shortener.py", line 236, in usage
    usages = list(mapper(self._usage, tokens))
  File "/workspaces/bitlyshortener/bitlyshortener/shortener.py", line 198, in _usage
    orgs = response.json()["organizations"]
KeyError: 'organizations'
```

I am investigating.

**Comment by manojsitapara** [comment]
I have created these tokens 2 days ago and never used earlier.

**Comment by impredicative** [comment]
@manojsitapara Basically the first token (which is not working) is an invalid token. I keep getting the error `NOT_AUTHORIZED` for it. I advise you discard and regenerate it, and be careful when noting it.

The second token has no issue.

**Comment by manojsitapara** [comment]
I am sorry I will double check next time !! But can we add exception handler to skip such token, in case if users added invalid token?

**Comment by impredicative** [comment]
I do not feel a strong need for that yet. I have used tokens for years, and have never had a single such issue with any token. I think you just need to be careful when saving them.

**Comment by impredicative** [comment]
I have however now released a new version which adds a safety check when checking usage. Please use this new version. Refer to the [release notes](https://github.com/impredicative/bitlyshortener/releases/tag/0.6.2) for it.
