### ISSUE TITLE
[feature request] shorten URL with SSL

### ISSUE THREAD

**Issue by mkschulze** [impredicative/bitlyshortener#3]
Would it be possible, to append an s to http:// somehow programmatically?

Because bit.ly provides ssl links only with the premium account (branded links) and otherwise it would be required to copy the generated URL and append an s manually.

If this could be added to the package, it would be pretty nice.

What do you think?

**Comment by impredicative** [comment]
If you see the examples in the readme, this and more was implemented long ago.

**Comment by mkschulze** [comment]
oh, pardon me.
