### ISSUE TITLE
[feature request] utf-8 support

### ISSUE THREAD

**Issue by mkschulze** [impredicative/bitlyshortener#4]
Not sure if the bit.ly API supports this, but it would be great to be able to generate URLs also from letters like [ä,ö,ü,§,%,"], so having utf-8 support would be nice.

**Comment by impredicative** [comment]
Do you mean for the short URL? In that case, no, it's not supported and probably never will be. The reason is that such fancy characters are more wasteful of bits and are therefore less efficient to store and to transmit. I agree though that the URL will look shorter.

Anyway, the nature of the short URL is beyond the scope of this package. I have no control over what they provide.

**Comment by mkschulze** [comment]
I mean like in my table example, when i want to shorten an URL with special characters.

The following examples mostly work, but some do not generate an URL. Those throw an error instead. I think supporting utf-8 encoding would be useful here.

> Bad Request for url: https://api-ssl.bitly.com/v4/shorten

![Bildschirmfoto 2019-05-06 um 21 39 51](https://user-images.githubusercontent.com/3390820/57250387-98335280-7047-11e9-901e-b008ef345ba1.png)

here is the log from shortening this url http://127.0.0.1:5000/newrequest/%$§
https://gist.github.com/mark-schulze/4002e71525c799ed1930517fec0c8b7a

Or maybe it is a security issue passing certain symbols?

**Comment by impredicative** [comment]
Unicode characters in the long URL are not a problem; they are supported fine afaik. I believe it's the % sign that is the problem; it's problematic to use in a URL. I recommend avoiding the percentage sign. If you really want to use it, refer to the methods [here](https://docs.python.org/3/library/urllib.parse.html#url-quoting) but I recommend you don't.

**Comment by mkschulze** [comment]
Ok, I will validate it out then I guess. thx for the hint.

**Comment by impredicative** [comment]
Yes, let me know if there any other errors.
