### ISSUE TITLE
[feature request] analytics

### ISSUE THREAD

**Issue by 2YoungKim** [impredicative/bitlyshortener#5]
It would be great to have an analytics feature for getting the number of clicks as well.

**Comment by impredicative** [comment]
I'm sorry but getting analytics will never be implemented in this package. I understand that analytics are useful, but I consider it well beyond the scope and priorities of this package. The scope of this package is limited to shortening only. I have previously noted in the readme:

> Other Bitly operations are outside the scope of this package.

I encourage you to implement it in a different package. It could take as input a list or series of short URLs, the corresponding bitly token, and return a dataframe or list of dicts or such with analytics for the same.

Note that bitlyshortener allows the use of multiple bitly tokens for shortening, but this can present a difficulty when looking up analytics. If you don't know which token was randomly used for which short URL, I think this might make it harder to get analytics. This problem may present itself only if multiple bitly tokens are used with bitlyshortener. I haven't really looked into getting analytics so I'm just speculating.

**Comment by impredicative** [comment]
As an aside, if you need a recommendation for a paid consultant who can develop the necessary software for you, I can recommend someone, but it can cost quite a bit. Please note that I have no financial conflict of interest in the matter.
