### ISSUE TITLE
Could not find a version that satisfies the requirement

### ISSUE THREAD

**Issue by macperez** [impredicative/bitlyshortener#6]
Hey, I am trying to install this library inside a Docker container but I have always the same error: 

```docker run -it --entrypoint=/bin/bash sciencepod-testingroot@8022d008f48a:/app# pip3 install bitlyshortener
Collecting bitlyshortener
  Could not find a version that satisfies the requirement bitlyshortener (from versions: )
No matching distribution found for bitlyshortener
root@8022d008f48a:/app# 
```

any idea by there?

**Comment by impredicative** [comment]
It requires Python >= 3.7.

**Comment by macperez** [comment]
Ok. it's works. Thank you very much!

**Comment by impredicative** [comment]
If you use it a lot, remember to track your usage at https://app.bitly.com/organization/1/detail

Use sufficient tokens so you don't max out the usage for any one token.
