### ISSUE TITLE
An option to use something other than j.mp domain for the short links?

### ISSUE THREAD

**Issue by atishayjain708** [impredicative/bitlyshortener#8]
I wanted to try to create an option to use the usual bit.ly or some other (possibly, user-supplied) custom domain instead of the default j.mp being used in the shortened link. Any way to do this?

**Comment by impredicative** [comment]
No, but you get a string back, so you can just call `short_url.replace('https://j.mp/', 'https://bit.ly/', 1)`, etc.

**Comment by impredicative** [comment]
You may wish to refer to the optional `vanitize=True` feature documented in the readme. This adds support for custom domains, e.g. `cnn.it`, `amzn.to`, etc. User supplied custom domains are not supported.

**Comment by impredicative** [comment]
v0.5.0 always in effect uses the available vanity domain. That's because forcing the j.mp or bit.ly URLs for vanity domains is no longer supported by Bitly. Refer to the examples in the readme.
